# Generated by Django 6.0.7 on 2026-07-27 20:59

import banners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=500)),
                ('icon', models.CharField(choices=[('star', 'Estrella'), ('heart', 'Corazón'), ('people', 'Comunidad'), ('book', 'Biblia'), ('calendar', 'Calendario'), ('cross', 'Cruz')], default='star', max_length=20)),
                ('button_text', models.CharField(blank=True, max_length=60)),
                ('button_url', models.CharField(blank=True, max_length=500, validators=[banners.models.validate_banner_url])),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'ordering': ('position', 'id'),
            },
        ),
    ]
