# Generated by Django 6.0.7 on 2026-07-27 21:12

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=3000),
        ),
    ]
