# Generated by Django 6.0.7 on 2026-08-03 05:50

import django_ckeditor_5.fields
from django.db import migrations, models
from django.db.models import F


def copy_spanish_content(apps, schema_editor):
    Banner = apps.get_model('banners', 'Banner')
    Banner.objects.update(
        title_es=F('title'),
        description_es=F('description'),
        button_text_es=F('button_text'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_banner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text_es',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text_pt',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_es',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_pt',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_es',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_pt',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.RunPython(copy_spanish_content, migrations.RunPython.noop),
    ]
