# Generated by Django 6.0.7 on 2026-07-27 21:35

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Próximo encuentro', max_length=60)),
                ('starts_at', models.DateTimeField()),
                ('admission_text', models.CharField(default='Entrada libre', max_length=80)),
                ('cta_text', models.CharField(default='Reservar mi lugar', max_length=80)),
                ('cta_url', models.CharField(default='#contacto', max_length=500, validators=[events.models.validate_event_url])),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ('starts_at', 'id'),
            },
        ),
    ]
