# Generated by Django 6.0.7 on 2026-07-27 21:35

from datetime import datetime
from zoneinfo import ZoneInfo

from django.db import migrations


def seed_initial_events(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    event_timezone = ZoneInfo("America/New_York")
    dates = (
        (datetime(2026, 10, 12, 19, 0, tzinfo=event_timezone), True),
        (datetime(2026, 11, 28, 19, 0, tzinfo=event_timezone), False),
        (datetime(2026, 12, 5, 19, 0, tzinfo=event_timezone), False),
        (datetime(2027, 1, 18, 19, 0, tzinfo=event_timezone), False),
    )

    Event.objects.bulk_create(
        [
            Event(
                eyebrow="Próximo encuentro",
                starts_at=starts_at,
                admission_text="Entrada libre",
                cta_text="Reservar mi lugar",
                cta_url="#contacto",
                is_featured=is_featured,
                is_published=True,
            )
            for starts_at, is_featured in dates
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            seed_initial_events,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
