# Generated by Django 6.0.7 on 2026-07-27 21:35

from datetime import datetime, timedelta, timezone

from django.db import migrations


def seed_initial_events(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    # Keep this historical migration compatible with Python 3.8. The seeded
    # dates are fixed, so their New York UTC offsets can be stored explicitly:
    # October 12 is in daylight time and the remaining dates are standard time.
    daylight_time = timezone(timedelta(hours=-4), name="EDT")
    standard_time = timezone(timedelta(hours=-5), name="EST")
    dates = (
        (datetime(2026, 10, 12, 19, 0, tzinfo=daylight_time), True),
        (datetime(2026, 11, 28, 19, 0, tzinfo=standard_time), False),
        (datetime(2026, 12, 5, 19, 0, tzinfo=standard_time), False),
        (datetime(2027, 1, 18, 19, 0, tzinfo=standard_time), False),
    )

    Event.objects.bulk_create(
        [
            Event(
                eyebrow="Próximo encuentro",
                starts_at=starts_at,
                admission_text="Entrada libre",
                cta_text="Reservar mi lugar",
                cta_url="#contacto",
                is_featured=is_featured,
                is_published=True,
            )
            for starts_at, is_featured in dates
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            seed_initial_events,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
