# Generated by Django 6.0.7 on 2026-07-27

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_seed_initial_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        max_length=500,
                        validators=[events.models.validate_youtube_url],
                        verbose_name="enlace de YouTube",
                    ),
                ),
                (
                    "youtube_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=11,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=250,
                    ),
                ),
                (
                    "channel_title",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=200,
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        editable=False,
                        max_length=500,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "api_synced_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("show_on_home", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "video de YouTube",
                "verbose_name_plural": "videos de YouTube",
                "ordering": (
                    "position",
                    "-published_at",
                    "-created_at",
                ),
            },
        ),
    ]
