# Generated by Django 6.0.7 on 2026-08-03 05:50

from django.db import migrations, models
from django.db.models import F


def prepare_translated_event_content(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    Event.objects.update(
        eyebrow_es=F('eyebrow'),
        admission_text_es=F('admission_text'),
        cta_text_es=F('cta_text'),
        eyebrow_en=None,
        admission_text_en=None,
        cta_text_en=None,
        eyebrow_pt=None,
        admission_text_pt=None,
        cta_text_pt=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_youtubevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admission_text_en',
            field=models.CharField(default='Entrada libre', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='admission_text_es',
            field=models.CharField(default='Entrada libre', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='admission_text_pt',
            field=models.CharField(default='Entrada libre', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cta_text_en',
            field=models.CharField(default='Reservar mi lugar', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cta_text_es',
            field=models.CharField(default='Reservar mi lugar', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cta_text_pt',
            field=models.CharField(default='Reservar mi lugar', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eyebrow_en',
            field=models.CharField(default='Próximo encuentro', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eyebrow_es',
            field=models.CharField(default='Próximo encuentro', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eyebrow_pt',
            field=models.CharField(default='Próximo encuentro', max_length=60, null=True),
        ),
        migrations.RunPython(
            prepare_translated_event_content,
            migrations.RunPython.noop,
        ),
    ]
