# Generated by Django 6.0.7 on 2026-08-03 05:50

from django.db import migrations, models
from django.db.models import F


def copy_spanish_content(apps, schema_editor):
    GalleryImage = apps.get_model('gallery', 'GalleryImage')
    GalleryImage.objects.update(
        title_es=F('title'),
        description_es=F('description'),
        alt_text_es=F('alt_text'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='alt_text_en',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='alt_text_es',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='alt_text_pt',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_en',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_es',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_pt',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_en',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_es',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_pt',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.RunPython(copy_spanish_content, migrations.RunPython.noop),
    ]
