# Generated by Django 6.0.7 on 2026-07-27

import donations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DonationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paypal_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        validators=[donations.models.validate_paypal_url],
                        verbose_name="enlace de PayPal",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "configuración de donaciones",
                "verbose_name_plural": "configuración de donaciones",
            },
        ),
    ]

