# Generated by Django 6.0.7 on 2026-08-04 11:07

import django.core.validators
import guests.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpecialGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("role", models.CharField(blank=True, max_length=140)),
                (
                    "role_es",
                    models.CharField(blank=True, max_length=140, null=True),
                ),
                (
                    "role_en",
                    models.CharField(blank=True, max_length=140, null=True),
                ),
                (
                    "role_pt",
                    models.CharField(blank=True, max_length=140, null=True),
                ),
                ("description", models.TextField(max_length=360)),
                (
                    "description_es",
                    models.TextField(max_length=360, null=True),
                ),
                (
                    "description_en",
                    models.TextField(max_length=360, null=True),
                ),
                (
                    "description_pt",
                    models.TextField(max_length=360, null=True),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=guests.models.guest_photo_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=("jpg", "jpeg", "png", "webp")
                            )
                        ],
                    ),
                ),
                ("alt_text", models.CharField(max_length=180)),
                (
                    "alt_text_es",
                    models.CharField(max_length=180, null=True),
                ),
                (
                    "alt_text_en",
                    models.CharField(max_length=180, null=True),
                ),
                (
                    "alt_text_pt",
                    models.CharField(max_length=180, null=True),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "invitado especial",
                "verbose_name_plural": "invitados especiales",
                "ordering": ("position", "name", "id"),
            },
        ),
    ]
