# Generated by Django 6.0.7 on 2026-08-04 11:23

import django.db.models.deletion
from django.db import migrations, models


def create_default_category(apps, schema_editor):
    ShowcaseCategory = apps.get_model("guests", "ShowcaseCategory")
    ShowcaseItem = apps.get_model("guests", "ShowcaseItem")
    category = ShowcaseCategory.objects.create(
        title="Invitados especiales",
        title_es="Invitados especiales",
        title_en="Special guests",
        title_pt="Convidados especiais",
        headline="Voces que inspiran.",
        headline_es="Voces que inspiran.",
        headline_en="Voices that inspire.",
        headline_pt="Vozes que inspiram.",
        accent="Historias que acercan.",
        accent_es="Historias que acercan.",
        accent_en="Stories that bring us closer.",
        accent_pt="Histórias que aproximam.",
        description=(
            "Conoce a las personas que nos acompañarán para compartir un "
            "mensaje de fe, propósito y esperanza."
        ),
        description_es=(
            "Conoce a las personas que nos acompañarán para compartir un "
            "mensaje de fe, propósito y esperanza."
        ),
        description_en=(
            "Meet the people joining us to share a message of faith, "
            "purpose, and hope."
        ),
        description_pt=(
            "Conheça as pessoas que nos acompanharão para partilhar uma "
            "mensagem de fé, propósito e esperança."
        ),
        position=0,
        is_active=True,
    )
    ShowcaseItem.objects.filter(category__isnull=True).update(category=category)


def remove_default_category(apps, schema_editor):
    ShowcaseCategory = apps.get_model("guests", "ShowcaseCategory")
    ShowcaseItem = apps.get_model("guests", "ShowcaseItem")
    ShowcaseItem.objects.update(category=None)
    ShowcaseCategory.objects.filter(
        title_es="Invitados especiales",
        position=0,
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("guests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowcaseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("title_es", models.CharField(max_length=120, null=True)),
                ("title_en", models.CharField(max_length=120, null=True)),
                ("title_pt", models.CharField(max_length=120, null=True)),
                ("headline", models.CharField(max_length=170)),
                ("headline_es", models.CharField(max_length=170, null=True)),
                ("headline_en", models.CharField(max_length=170, null=True)),
                ("headline_pt", models.CharField(max_length=170, null=True)),
                ("accent", models.CharField(blank=True, max_length=170)),
                (
                    "accent_es",
                    models.CharField(blank=True, max_length=170, null=True),
                ),
                (
                    "accent_en",
                    models.CharField(blank=True, max_length=170, null=True),
                ),
                (
                    "accent_pt",
                    models.CharField(blank=True, max_length=170, null=True),
                ),
                ("description", models.TextField(max_length=500)),
                ("description_es", models.TextField(max_length=500, null=True)),
                ("description_en", models.TextField(max_length=500, null=True)),
                ("description_pt", models.TextField(max_length=500, null=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "categoría destacada",
                "verbose_name_plural": "categorías destacadas",
                "ordering": ("position", "title", "id"),
            },
        ),
        migrations.RenameModel(
            old_name="SpecialGuest",
            new_name="ShowcaseItem",
        ),
        migrations.AddField(
            model_name="showcaseitem",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="guests.showcasecategory",
            ),
        ),
        migrations.AlterModelOptions(
            name="showcaseitem",
            options={
                "ordering": ("position", "name", "id"),
                "verbose_name": "tarjeta destacada",
                "verbose_name_plural": "tarjetas destacadas",
            },
        ),
        migrations.RunPython(create_default_category, remove_default_category),
        migrations.AlterField(
            model_name="showcaseitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="guests.showcasecategory",
            ),
        ),
    ]
