# Generated by Django 6.0.7 on 2026-09-09 15:41

import django.core.validators
import guests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_seed_locations_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('profile_type', models.CharField(choices=[('pastor', 'Pastor'), ('guest', 'Invitado especial'), ('leader', 'Líder ministerial')], default='pastor', max_length=20)),
                ('role', models.CharField(max_length=170)),
                ('role_es', models.CharField(max_length=170, null=True)),
                ('role_en', models.CharField(max_length=170, null=True)),
                ('role_pt', models.CharField(max_length=170, null=True)),
                ('introduction', models.TextField(max_length=500)),
                ('introduction_es', models.TextField(max_length=500, null=True)),
                ('introduction_en', models.TextField(max_length=500, null=True)),
                ('introduction_pt', models.TextField(max_length=500, null=True)),
                ('biography', models.TextField(max_length=5000)),
                ('biography_es', models.TextField(max_length=5000, null=True)),
                ('biography_en', models.TextField(max_length=5000, null=True)),
                ('biography_pt', models.TextField(max_length=5000, null=True)),
                ('photo', models.ImageField(upload_to=guests.models.ministry_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'))])),
                ('alt_text', models.CharField(max_length=180)),
                ('alt_text_es', models.CharField(max_length=180, null=True)),
                ('alt_text_en', models.CharField(max_length=180, null=True)),
                ('alt_text_pt', models.CharField(max_length=180, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'perfil ministerial',
                'verbose_name_plural': 'perfiles ministeriales',
                'ordering': ('position', 'name', 'id'),
            },
        ),
    ]
